<?php 
	$_prev = $this->getPreviousProductArray();
	$_next = $this->getNextProductArray(); 
?>

<?php if ($_prev || $_next): ?>
	<?php if ($_prev): ?> 
		<a class="prev-prod" href="<?php echo $_prev['url'] ?>" title="<?php echo $_prev['name'] ?>">
			<?php echo $this->__('<- Producto anterior');?>
		</a>
	<?php endif; ?>

	<?php if ($_next): ?>
		<a class="next-prod" href="<?php echo $_next['url'] ?>" title="<?php echo $_next['name'] ?>">
			<?php echo $this->__('Producto siguiente ->');?>
		</a>
	<?php endif; ?>
<?php endif; ?>